resolver: lts-12.16
packages:
- .
extra-deps:
- ../mxnet-hs/base
- ../mxnet-hs/operators
- ../mxnet-nn
- ../mxnet-dataiter/dataiter
- ../tuple-ops
- git: https://github.com/kylcarte/type-combinators.git
  commit: 071942730b6bb34990d37e1a25236382cf0dcbc6
- git: https://github.com/pierric/haskell-src-exts.git
  commit: f75a5dbe2ec9fbc67df0936333e0665b033f9e22
- c2hs-extra-0.1.0.1
- streaming-utils-0.1.4.7
- graphviz-2999.20.0.2
- fgl-5.5.4.0
extra-include-dirs:
- /home/jiasen/incubator-mxnet/include
- /home/jiasen/incubator-mxnet/nnvm/include/
extra-lib-dirs:
- /home/jiasen/incubator-mxnet/lib
