resolver: lts-14.27

#setup-info:
#  ghc:
#    linux64-custom-dwarf-tinfo6:
#      8.6.5:
#        url: "https://downloads.haskell.org/~ghc/8.6.5/ghc-8.6.5-x86_64-deb9-linux-dwarf.tar.xz"
#        #sha256: f9cac6e402c71d7251f2e22f412fb4abd72c64f34481a1e548cd7f6ff2352a07
#ghc-variant: dwarf
ghc-options:
    "$everything": -threaded
    "fei-examples": -rtsopts
packages:
- .
- ../fei-base
- ../fei-nn
- ../fei-cocoapi
- ../fei-datasets
- ../fei-modelzoo
- ../tuple-ops
extra-deps:
- git: https://github.com/0xCM/type-combinators.git
  commit: 58167dd4017b666ff592bb9493b0570a054aabdb
- git: https://github.com/pierric/haskell-src-exts.git
  commit: f75a5dbe2ec9fbc67df0936333e0665b033f9e22
- JuicyPixels-repa-0.7.1.0
- hip-1.5.4.0
- ghcide-0.2.0
- fuzzy-0.1.0.0
- ghc-check-0.3.0.1
- haddock-library-1.9.0
- haskell-lsp-0.22.0.0
- haskell-lsp-types-0.22.0.0
- hie-bios-0.5.0
- regex-tdfa-1.3.1.0
- regex-base-0.94.0.0
extra-include-dirs:
- /home/jiasen/workspace/mxnet/build-1.6.0/include
extra-lib-dirs:
- /home/jiasen/workspace/mxnet/build-1.6.0
flags:
    fei-base:
        mxnet_geq_10600: true
    fei-nn:
        mxnet_geq_10600: true

